import matplotlib.pyplot as plt
import numpy as np 

plt.figure(1)
profile = np.loadtxt('output/two_point_b0_m0.txt')
plt.imshow(profile, interpolation=None, cmap=plt.cm.Blues)
plt.xlabel("$l_1-1$")
plt.ylabel("$l_2-1$")
plt.title("$\\left\\|\\left\\langle\\epsilon_{0,l_1}\\epsilon_{0,l_2}^{*}\\right\\rangle\\right\\|$")
plt.colorbar()
plt.savefig("plots/tow_point_modules_b0_m0.pdf", format='pdf', bbox_inches = "tight")

plt.figure(2)
profile = np.loadtxt('output/two_point_b0_m1.txt')
plt.imshow(profile, interpolation=None, cmap=plt.cm.Blues)
plt.xlabel("$l_1-1$")
plt.ylabel("$l_2-1$")
plt.title("$\\left\\|\\left\\langle\\epsilon_{1,l_1}\\epsilon_{1,l_2}^{*}\\right\\rangle\\right\\|$")
plt.colorbar()
plt.savefig("plots/tow_point_modules_b0_m1.pdf", format='pdf', bbox_inches = "tight")

plt.figure(3)
profile = np.loadtxt('output/two_point_b0_m2.txt')
plt.imshow(profile, interpolation=None, cmap=plt.cm.Blues)
plt.xlabel("$l_1-1$")
plt.ylabel("$l_2-1$")
plt.title("$\\left\\|\\left\\langle\\epsilon_{2,l_1}\\epsilon_{2,l_2}^{*}\\right\\rangle\\right\\|$")
plt.colorbar()
plt.savefig("plots/tow_point_modules_b0_m2.pdf", format='pdf', bbox_inches = "tight")

plt.figure(4)
profile = np.loadtxt('output/two_point_b0_m3.txt')
plt.imshow(profile, interpolation=None, cmap=plt.cm.Blues)
plt.xlabel("$l_1-1$")
plt.ylabel("$l_2-1$")
plt.title("$\\left\\|\\left\\langle\\epsilon_{3,l_1}\\epsilon_{3,l_2}^{*}\\right\\rangle\\right\\|$")
plt.colorbar()
plt.savefig("plots/tow_point_modules_b0_m3.pdf", format='pdf', bbox_inches = "tight")

plt.figure(5)
profile = np.loadtxt('output/two_point_b0_m4.txt')
plt.imshow(profile, interpolation=None, cmap=plt.cm.Blues)
plt.xlabel("$l_1-1$")
plt.ylabel("$l_2-1$")
plt.title("$\\left\\|\\left\\langle\\epsilon_{4,l_1}\\epsilon_{4,l_2}^{*}\\right\\rangle\\right\\|$")
plt.colorbar()
plt.savefig("plots/tow_point_modules_b0_m4.pdf", format='pdf', bbox_inches = "tight")

plt.figure(6)
profile = np.loadtxt('output/two_point_b0_m5.txt')
plt.imshow(profile, interpolation=None, cmap=plt.cm.Blues)
plt.xlabel("$l_1-1$")
plt.ylabel("$l_2-1$")
plt.title("$\\left\\|\\left\\langle\\epsilon_{5,l_1}\\epsilon_{5,l_2}^{*}\\right\\rangle\\right\\|$")
plt.colorbar()
plt.savefig("plots/tow_point_modules_b0_m5.pdf", format='pdf', bbox_inches = "tight")

plt.figure(7)
profile = np.loadtxt('output/two_point_b0_m6.txt')
plt.imshow(profile, interpolation=None, cmap=plt.cm.Blues)
plt.xlabel("$l_1-1$")
plt.ylabel("$l_2-1$")
plt.title("$\\left\\|\\left\\langle\\epsilon_{6,l_1}\\epsilon_{6,l_2}^{*}\\right\\rangle\\right\\|$")
plt.colorbar()
plt.savefig("plots/tow_point_modules_b0_m6.pdf", format='pdf', bbox_inches = "tight")

plt.figure(8)
profile = np.loadtxt('output/two_point_b0_m7.txt')
plt.imshow(profile, interpolation=None, cmap=plt.cm.Blues)
plt.xlabel("$l_1-1$")
plt.ylabel("$l_2-1$")
plt.title("$\\left\\|\\left\\langle\\epsilon_{7,l_1}\\epsilon_{7,l_2}^{*}\\right\\rangle\\right\\|$")
plt.colorbar()
plt.savefig("plots/tow_point_modules_b0_m7.pdf", format='pdf', bbox_inches = "tight")

plt.figure(9)
profile = np.loadtxt('output/two_point_b0_m8.txt')
plt.imshow(profile, interpolation=None, cmap=plt.cm.Blues)
plt.xlabel("$l_1-1$")
plt.ylabel("$l_2-1$")
plt.title("$\\left\\|\\left\\langle\\epsilon_{8,l_1}\\epsilon_{8,l_2}^{*}\\right\\rangle\\right\\|$")
plt.colorbar()
plt.savefig("plots/tow_point_modules_b0_m8.pdf", format='pdf', bbox_inches = "tight")

plt.figure(10)
profile = np.loadtxt('output/two_point_b0_m9.txt')
plt.imshow(profile, interpolation=None, cmap=plt.cm.Blues)
plt.xlabel("$l_1-1$")
plt.ylabel("$l_2-1$")
plt.title("$\\left\\|\\left\\langle\\epsilon_{9,l_1}\\epsilon_{9,l_2}^{*}\\right\\rangle\\right\\|$")
plt.colorbar()
plt.savefig("plots/tow_point_modules_b0_m9.pdf", format='pdf', bbox_inches = "tight")


