import matplotlib.pyplot as plt 
import numpy as np 

r0, e0, de0 = np.loadtxt("output/energies_averaged00.txt", unpack=True)
r1, e1, de1 = np.loadtxt("output/energies_averaged02.txt", unpack=True)
r2, e2, de2 = np.loadtxt("output/energies_averaged04.txt", unpack=True)
r3, e3, de3 = np.loadtxt("output/energies_averaged05.txt", unpack=True)
r4, e4, de4 = np.loadtxt("output/energies_averaged06.txt", unpack=True)
r5, e5, de5 = np.loadtxt("output/energies_averaged07.txt", unpack=True)
r6, e6, de6 = np.loadtxt("output/energies_averaged08.txt", unpack=True)
r7, e7, de7 = np.loadtxt("output/energies_averaged09.txt", unpack=True)
r8, e8, de8 = np.loadtxt("output/energies_averaged10.txt", unpack=True)
r9, e9, de9 = np.loadtxt("output/energies_averaged11.txt", unpack=True)


plt.plot(r0, e0+de0, linewidth = 0.5, color = "blue")
plt.plot(r0, e0-de0, linewidth = 0.5, color = "blue")
plt.fill_between(r0, e0+de0, e0-de0, color = "blue", label="$b = $0 fm")
plt.plot(r1, e1+de1, linewidth = 0.5, color = "orange")
plt.plot(r1, e1-de1, linewidth = 0.5, color = "orange")
plt.fill_between(r1, e1+de1, e1-de1, color = "orange", label="$b = $2 fm")
plt.plot(r2, e2+de2, linewidth = 0.5, color = "green")
plt.plot(r2, e2-de2, linewidth = 0.5, color = "green")
plt.fill_between(r2, e2+de2, e2-de2, color = "green", label="$b = $4 fm")
plt.plot(r3, e3+de3, linewidth = 0.5, color = "red")
plt.plot(r3, e3-de3, linewidth = 0.5, color = "red")
plt.fill_between(r3, e3+de3, e3-de3, color = "red", label="$b = $5 fm")
plt.plot(r4, e4+de4, linewidth = 0.5, color = "purple")
plt.plot(r4, e4-de4, linewidth = 0.5, color = "purple")
plt.fill_between(r4, e4+de4, e4-de4, color = "purple", label="$b = $6 fm")
plt.plot(r5, e5+de5, linewidth = 0.5, color = "brown")
plt.plot(r5, e5-de5, linewidth = 0.5, color = "brown")
plt.fill_between(r5, e5+de5, e5-de5, color = "brown", label="$b = $7 fm")
plt.plot(r6, e6+de6, linewidth = 0.5, color = "pink")
plt.plot(r6, e6-de6, linewidth = 0.5, color = "pink")
plt.fill_between(r6, e6+de6, e6-de6, color = "pink", label="$b = $8 fm")
plt.plot(r7, e7+de7, linewidth = 0.5, color = "gray")
plt.plot(r7, e7-de7, linewidth = 0.5, color = "gray")
plt.fill_between(r7, e7+de7, e7-de7, color = "gray", label="$b = $9 fm")
plt.plot(r8, e8+de8, linewidth = 0.5, color = "olive")
plt.plot(r8, e8-de8, linewidth = 0.5, color = "olive")
plt.fill_between(r8, e8+de8, e8-de8, color = "olive", label="$b = $10 fm")
plt.plot(r9, e9+de9, linewidth = 0.5, color = "cyan")
plt.plot(r9, e9-de9, linewidth = 0.5, color = "cyan")
plt.fill_between(r9, e9+de9, e9-de9, color = "cyan", label="$b = $11 fm")

#plt.errorbar(r, e, yerr = de, linestyle = "none", capsize = 2 , color = "blue")
plt.xlabel("$r$ [fm]")
plt.ylabel("normalized energy density")
plt.legend(loc = "best")
plt.savefig("plots/energy-r.pdf", format="pdf", bbox_inches="tight")